# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: mse_lines_care_asym
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: reds-train
    type: PairedImageDataset
    # /home/youlab/Desktop/workspace/jiashu/neuroclear/simulation_test/final/pairwise/shift_var_rot_noise
    dataroot_gt: /home/youlab/Desktop/workspace/jiashu/datasets/simulation/asymmetry/xy
    dataroot_lq: /home/youlab/Desktop/workspace/jiashu/datasets/simulation/asymmetry/xy_lq

    # /home/youlab/Desktop/workspace/jiashu/datasets/final/asymmetrical/gt

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 500
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    
  val:
    name: reds-val300-test
    type: PairedImageDataset
    dataroot_gt: /home/youlab/Desktop/workspace/jiashu/neuroclear/simulation_test/final/pairwise/gt
    dataroot_lq: /home/youlab/Desktop/workspace/jiashu/neuroclear/simulation_test/final/pairwise/shift_var_rot_noise
    io_backend:
      type: disk


network_g:
  type: NAFNetLocal
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  
ZEST: True
# path
path:
  pretrain_network_g: ~
  # /home/youlab/Desktop/workspace/jiashu/NAFNet/experiments/pretrained_models/NAFNet-REDS-width64.pth
  # /home/youlab/Desktop/workspace/jiashu/datasets/simulation/final_exp/field_curvature/train/gt
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 2500
    eta_min: !!float 1e-7

  total_iter: 16000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2500
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: none
  port: 29500
